version: 0.1
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
  phases:
  install:
    runtime-versions: 
      php: 7.3
phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
  

